### ISSUE TITLE
`pip install pyobjus` fails on Mac OSX

### ISSUE THREAD

**Issue by vik748** [kivy/pyobjus#62] opened 2020-05-08 12:33 UTC
Running `pip install pyobjus` fails on mac with the following errors:

```
(mb_pc_env) Vik-MBP:multibeam_pointcloud_correction vik748$ pip install pyobjus
Collecting pyobjus
  Using cached https://files.pythonhosted.org/packages/cb/9e/6425d66cf66892ee99ebdc86204c825d6817458328b6cdc3a6c51ad152d1/pyobjus-1.1.0.tar.gz
Building wheels for collected packages: pyobjus
  Running setup.py bdist_wheel for pyobjus ... error
  Complete output from command /Users/vik748/anaconda3/envs/mb_pc_env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/qq/p75542c55gz41w8ycl_crgq40000gn/T/pip-install-6mtj74f6/pyobjus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/qq/p75542c55gz41w8ycl_crgq40000gn/T/pip-wheel-ldrgr6ie --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.5
  copying setup.py -> build/lib.macosx-10.6-x86_64-3.5
  creating build/lib.macosx-10.6-x86_64-3.5/pyobjus
  copying pyobjus/dylib_manager.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
  copying pyobjus/protocols.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
  copying pyobjus/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
  copying pyobjus/objc_py_types.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
  creating build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
  copying pyobjus/consts/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
  copying pyobjus/consts/corebluetooth.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
  running build_ext
  cythoning pyobjus/pyobjus.pyx to pyobjus/pyobjus.c
  /Users/vik748/anaconda3/envs/mb_pc_env/lib/python3.5/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/qq/p75542c55gz41w8ycl_crgq40000gn/T/pip-install-6mtj74f6/pyobjus/pyobjus/pyobjus.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pyobjus' extension
  creating build/temp.macosx-10.6-x86_64-3.5
  creating build/temp.macosx-10.6-x86_64-3.5/pyobjus
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/vik748/anaconda3/envs/mb_pc_env/include -arch x86_64 -I/Users/vik748/anaconda3/envs/mb_pc_env/include/python3.5m -c pyobjus/pyobjus.c -o build/temp.macosx-10.6-x86_64-3.5/pyobjus/pyobjus.o
  In file included from pyobjus/pyobjus.c:608:
  pyobjus/_runtime.h:33:23: error: too many arguments to function call, expected 0, have 2
    return objc_msgSend(pool, sel_registerName("init"));
           ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  In file included from pyobjus/pyobjus.c:608:
  pyobjus/_runtime.h:37:22: error: too many arguments to function call, expected 0, have 2
    (void)objc_msgSend(pool, sel_registerName("drain"));
          ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  pyobjus/pyobjus.c:24591:25: error: too many arguments to function call, expected 0, have 2
      (void)(objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"release"))));
             ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  pyobjus/pyobjus.c:24668:45: error: too many arguments to function call, expected 0, have 2
      __pyx_v_self->o_instance = objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"retain")));
                                 ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  4 errors generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyobjus
  Running setup.py clean for pyobjus
Failed to build pyobjus
Installing collected packages: pyobjus
  Running setup.py install for pyobjus ... error
    Complete output from command /Users/vik748/anaconda3/envs/mb_pc_env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/qq/p75542c55gz41w8ycl_crgq40000gn/T/pip-install-6mtj74f6/pyobjus/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/qq/p75542c55gz41w8ycl_crgq40000gn/T/pip-record-5jpuhtqs/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.5
    copying setup.py -> build/lib.macosx-10.6-x86_64-3.5
    creating build/lib.macosx-10.6-x86_64-3.5/pyobjus
    copying pyobjus/dylib_manager.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
    copying pyobjus/protocols.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
    copying pyobjus/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
    copying pyobjus/objc_py_types.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus
    creating build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
    copying pyobjus/consts/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
    copying pyobjus/consts/corebluetooth.py -> build/lib.macosx-10.6-x86_64-3.5/pyobjus/consts
    running build_ext
    skipping 'pyobjus/pyobjus.c' Cython extension (up-to-date)
    building 'pyobjus' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/pyobjus
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/vik748/anaconda3/envs/mb_pc_env/include -arch x86_64 -I/Users/vik748/anaconda3/envs/mb_pc_env/include/python3.5m -c pyobjus/pyobjus.c -o build/temp.macosx-10.6-x86_64-3.5/pyobjus/pyobjus.o
    In file included from pyobjus/pyobjus.c:608:
    pyobjus/_runtime.h:33:23: error: too many arguments to function call, expected 0, have 2
      return objc_msgSend(pool, sel_registerName("init"));
             ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
    OBJC_EXPORT void
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
    #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
    #       define OBJC_EXTERN extern
                               ^
    In file included from pyobjus/pyobjus.c:608:
    pyobjus/_runtime.h:37:22: error: too many arguments to function call, expected 0, have 2
      (void)objc_msgSend(pool, sel_registerName("drain"));
            ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
    OBJC_EXPORT void
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
    #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
    #       define OBJC_EXTERN extern
                               ^
    pyobjus/pyobjus.c:24591:25: error: too many arguments to function call, expected 0, have 2
        (void)(objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"release"))));
               ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
    OBJC_EXPORT void
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
    #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
    #       define OBJC_EXTERN extern
                               ^
    pyobjus/pyobjus.c:24668:45: error: too many arguments to function call, expected 0, have 2
        __pyx_v_self->o_instance = objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"retain")));
                                   ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
    OBJC_EXPORT void
    ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
    #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
    #       define OBJC_EXTERN extern
                               ^
    4 errors generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
```

**Comment by timtangcoding** [comment] 2020-05-24 15:35
I've got the same error. Does anyone how to fix this?

**Comment by pippyn** [comment] 2020-05-25 14:44
what worked for me was:
download [the zip of the repo](https://github.com/kivy/pyobjus/archive/master.zip) and unzip.
Open the `pyobjus` folder in terminal and run this command:
`python setup.py install`

**Comment by vik748** [comment] 2020-05-25 15:10
hmm, that worked for me too.  Wonder what `pip install` does so differently

**Comment by timtangcoding** [comment] 2020-05-31 05:56
It works for me too. Thanks a lot.

**Comment by sanderland** [comment] 2020-06-07 09:23
I also have users encounter this due to screeninfo needing pyobjus

**Comment by Zen-CODE** [comment] 2020-06-08 17:26
@sanderland . Please post the details of what happens when you try the above suggestions? Thanks. i.e. logs, exact error messages etc.

**Comment by sanderland** [comment] 2020-06-08 17:29
@Zen-CODE As I said, I do not have a mac, I merely see bug reports of users who encounter this issue with the same error message. As the repo seems to work, I assume it's just that a release is due (the last commit failed travis which may have blocked release?) and I asked @tshirtman about this, but he seemed a bit lost with the mac stuff as well.

**Comment by Zen-CODE** [comment] 2020-06-08 17:37
@sanderland. It's impossible to action anything without specifics. How can we solve a problem without knowing what the problem is?

But I get you position. Please try to capture a log of some sorts from your users so that we can reproduce the problem. Once we can reproduce it, we can solve it. But until then, it's just ether....

**Comment by vik748** [comment] 2020-06-08 17:41
I can get you what ever logs you need. I have posted the results of trying to run pip install on a Mac. What else do you need?

**Comment by sanderland** [comment] 2020-06-08 17:43
>Please try to capture a log of some sorts from your users

As I said, they are essentially the same as the ones posted by @vik748 . Please explain how posting multiple copies of the same problem will help you release the fix.

**Comment by Zen-CODE** [comment] 2020-06-08 17:44
@vik748. Thanks, but it works for you. So it's really just sanderlands issues that are unresolved?

**Comment by sanderland** [comment] 2020-06-08 17:44
```

Collecting katrain
  Using cached https://files.pythonhosted.org/packages/dd/ce/4d30b2e37fceacecc2a8af1dd0066fb8e1c0a49dd0f6388665218e4942bd/KaTrain-1.1.2-py3-none-any.whl
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (47.1.1)
Requirement already satisfied: pygame in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (1.9.6)
Requirement already satisfied: cython!=0.27,!=0.27.2,<=0.29.14,>=0.24 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (0.29.14)
Requirement already satisfied: kivy>=2.0.0rc2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (2.0.0rc2)
Requirement already satisfied: kivymd>=0.104.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (0.104.1)
Collecting screeninfo (from katrain)
Requirement already satisfied: wheel in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from katrain) (0.34.2)
Requirement already satisfied: docutils in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kivy>=2.0.0rc2->katrain) (0.16)
Requirement already satisfied: pygments in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kivy>=2.0.0rc2->katrain) (2.6.1)
Requirement already satisfied: Kivy-Garden>=0.1.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kivy>=2.0.0rc2->katrain) (0.1.4)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kivymd>=0.104.1->katrain) (2.23.0)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from kivymd>=0.104.1->katrain) (7.1.2)
Collecting pyobjus; sys_platform == "darwin" (from screeninfo->katrain)
  Using cached https://files.pythonhosted.org/packages/cb/9e/6425d66cf66892ee99ebdc86204c825d6817458328b6cdc3a6c51ad152d1/pyobjus-1.1.0.tar.gz
Requirement already satisfied: dataclasses in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from screeninfo->katrain) (0.6)
Requirement already satisfied: chardet<4,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->kivymd>=0.104.1->katrain) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->kivymd>=0.104.1->katrain) (2.9)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->kivymd>=0.104.1->katrain) (2020.4.5.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->kivymd>=0.104.1->katrain) (1.25.9)
Building wheels for collected packages: pyobjus
  Building wheel for pyobjus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-wheel-itch8t2w --python-tag cp37
       cwd: /private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/
  Complete output (74 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  copying setup.py -> build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/pyobjus
  copying pyobjus/dylib_manager.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus
  copying pyobjus/protocols.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus
  copying pyobjus/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus
  copying pyobjus/objc_py_types.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus
  creating build/lib.macosx-10.9-x86_64-3.7/pyobjus/consts
  copying pyobjus/consts/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus/consts
  copying pyobjus/consts/corebluetooth.py -> build/lib.macosx-10.9-x86_64-3.7/pyobjus/consts
  running build_ext
  cythoning pyobjus/pyobjus.pyx to pyobjus/p

yobjus.c
  /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/pyobjus/pyobjus.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pyobjus' extension
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/pyobjus
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c pyobjus/pyobjus.c -o build/temp.macosx-10.9-x86_64-3.7/pyobjus/pyobjus.o
  In file included from pyobjus/pyobjus.c:606:
  pyobjus/_runtime.h:33:23: error: too many arguments to function call, expected 0, have 2
    return objc_msgSend(pool, sel_registerName("init"));
           ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  In file included from pyobjus/pyobjus.c:606:
  pyobjus/_runtime.h:37:22: error: too many arguments to function call, expected 0, have 2
    (void)objc_msgSend(pool, sel_registerName("drain"));
          ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  pyobjus/pyobjus.c:24580:25: error: too many arguments to function call, expected 0, have 2
      (void)(objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"release"))));
             ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  pyobjus/pyobjus.c:24657:45: error: too many arguments to function call, expected 0, have 2
      __pyx_v_self->o_instance = objc_msgSend(__pyx_v_self->o_instance, sel_registerName(((char *)"retain")));
                                 ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:62:1: note: 'objc_msgSend' declared here
  OBJC_EXPORT void
  ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:236:25: note: expanded from macro 'OBJC_EXPORT'
  #   define OBJC_EXPORT  OBJC_EXTERN OBJC_VISIBLE
                          ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/objc-api.h:225:28: note: expanded from macro 'OBJC_EXTERN'
  #       define OBJC_EXTERN extern
                             ^
  4 errors generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyobjus
  Running setup.py clean for pyobjus
Failed to build pyobjus
Installing collected packages: pyobjus, screeninfo, katrain
  Running setup.py install for pyobjus ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/6rnssl091g94ybn7xdhhmvd40000gn/T/pip-install-9j56662v/pyobjus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --r
```

**Comment by sanderland** [comment] 2020-06-08 17:47
> @vik748. Thanks, but it works for you. So it's really just sanderlands issues that are unresolved?

He installed from master, not pypi, so I assume it's fixed and just not released. Hence my suggestion of releasing said fix.

**Comment by misl6** [comment] 2020-06-08 18:43
This issue is got fixed by https://github.com/kivy/pyobjus/commit/a10564c1ad3187518cc68855f9a6395e66aa08d1

Building from master should work. It simply needs a release.

**Comment by Zen-CODE** [comment] 2020-08-17 09:30
@vik748 Seems this issue is resolved. Please re-open if not. Thanks.

**Closed by Zen-CODE** 2020-08-17 09:30 UTC
